INSERT INTO MEMBER (USER_NO, USER_TYPE, USER_ID, USER_PWD, EMAIL, EROLL_DATE, MODIFY_DATE, STATUS)
VALUES (SEQ_UNO.NEXTVAL, 'U', 'user1', 'user1234', 'user1@example.com', SYSDATE, SYSTIMESTAMP, 'Y');

-- 신입 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '신입', '신입 게시글 제목 1', '신입 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 15, 2, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '신입', '신입 게시글 제목 2', '신입 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 25, 5, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '신입', '신입 게시글 제목 3', '신입 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 30, 3, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '신입', '신입 게시글 제목 4', '신입 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 40, 7, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '신입', '신입 게시글 제목 5', '신입 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 50, 9, 'Y');

-- 채용공고 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '채용공고', '채용공고 게시글 제목 1', '채용공고 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 20, 4, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '채용공고', '채용공고 게시글 제목 2', '채용공고 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 35, 6, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '채용공고', '채용공고 게시글 제목 3', '채용공고 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 45, 8, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '채용공고', '채용공고 게시글 제목 4', '채용공고 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 55, 10, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '채용공고', '채용공고 게시글 제목 5', '채용공고 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 65, 12, 'Y');


-- 취준 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '취준', '취준 게시글 제목 1', '취준 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 18, 3, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '취준', '취준 게시글 제목 2', '취준 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 28, 5, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '취준', '취준 게시글 제목 3', '취준 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 38, 7, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '취준', '취준 게시글 제목 4', '취준 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 48, 9, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '취준', '취준 게시글 제목 5', '취준 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 58, 11, 'Y');

-- 자소서 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자소서', '자소서 게시글 제목 1', '자소서 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 22, 4, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자소서', '자소서 게시글 제목 2', '자소서 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 32, 6, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자소서', '자소서 게시글 제목 3', '자소서 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 42, 8, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자소서', '자소서 게시글 제목 4', '자소서 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 52, 10, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자소서', '자소서 게시글 제목 5', '자소서 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 62, 12, 'Y');

-- 자격증 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자격증', '자격증 게시글 제목 1', '자격증 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 12, 2, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자격증', '자격증 게시글 제목 2', '자격증 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 22, 4, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자격증', '자격증 게시글 제목 3', '자격증 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 32, 6, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자격증', '자격증 게시글 제목 4', '자격증 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 42, 8, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '자격증', '자격증 게시글 제목 5', '자격증 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 52, 10, 'Y');

-- Q&A 카테고리 게시글 A대체 &A입력

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, 'Q&A', 'Q&A 게시글 제목 1', 'Q&A 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 14, 3, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, 'Q&A', 'Q&A 게시글 제목 2', 'Q&A 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 24, 5, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, 'Q&A', 'Q&A 게시글 제목 3', 'Q&A 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 34, 7, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, 'Q&A', 'Q&A 게시글 제목 4', 'Q&A 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 44, 9, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, 'Q&A', 'Q&A 게시글 제목 5', 'Q&A 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 54, 11, 'Y');
-- 커리어 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '커리어', '커리어 게시글 제목 1', '커리어 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 16, 3, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '커리어', '커리어 게시글 제목 2', '커리어 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 26, 5, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '커리어', '커리어 게시글 제목 3', '커리어 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 36, 7, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '커리어', '커리어 게시글 제목 4', '커리어 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 46, 9, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '커리어', '커리어 게시글 제목 5', '커리어 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 56, 11, 'Y');
-- 이직 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '이직', '이직 게시글 제목 1', '이직 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 17, 3, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '이직', '이직 게시글 제목 2', '이직 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 27, 5, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '이직', '이직 게시글 제목 3', '이직 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 37, 7, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '이직', '이직 게시글 제목 4', '이직 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 47, 9, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '이직', '이직 게시글 제목 5', '이직 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 57, 11, 'Y');
-- 잡담 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '잡담', '잡담 게시글 제목 1', '잡담 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 13, 2, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '잡담', '잡담 게시글 제목 2', '잡담 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 23, 4, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '잡담', '잡담 게시글 제목 3', '잡담 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 33, 6, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '잡담', '잡담 게시글 제목 4', '잡담 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 43, 8, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '잡담', '잡담 게시글 제목 5', '잡담 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 53, 10, 'Y');
-- 면접 카테고리 게시글

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '면접', '면접 게시글 제목 1', '면접 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 19, 3, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '면접', '면접 게시글 제목 2', '면접 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 29, 5, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '면접', '면접 게시글 제목 3', '면접 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 39, 7, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '면접', '면접 게시글 제목 4', '면접 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 49, 9, 'Y');

INSERT INTO POSTING (POSTING_NO, CATEGORY, TITLE, CONTENT, IMAGE, AUTHOR, USER_NO, CREATED_TIME, VIEW_COUNT, LIKE_COUNT, STATUS)
VALUES (POSTING_SEQ.NEXTVAL, '면접', '면접 게시글 제목 5', '면접 카테고리의 내용입니다.', NULL, 'admin', 1, SYSDATE, 59, 11, 'Y');

COMMIT;